- name: Install docker-compose
  hosts: all
  gather_facts: true

  tasks:
    - name: Download the Docker Compose binary from the repository
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture | lower }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create a symbolic link
      become: true
      ansible.builtin.file:
        dest: /usr/bin/docker-compose
        src: /usr/local/bin/docker-compose
        state: link
