- name: "Install dependent packages"
  become: true
  ansible.builtin.yum:
    update_cache: true
    name:
      - yum-utils
    state: present

- name: "Set up the repository"
  become: true
  ansible.builtin.yum_repository:
    name: docker-ce
    description: CentOS Docker CE Repository
    baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_version }}/{{ ansible_architecture }}/stable"
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: "Install Docker"
  become: true
  ansible.builtin.yum:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
