- name: Install dependent packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - ca-certificates
      - curl
    state: present

- name: Make dir for docker.asc
  ansible.builtin.file:
    path: /etc/apt/keyrings
    mode: '0755'
    state: directory

- name: Download Docker's official GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Determine the architecture
  ansible.builtin.set_fact:
    arch: >-
      {%- if ansible_architecture == 'aarch64' -%}
        arm64
      {%- elif ansible_architecture == 'x86_64' -%}
        amd64
      {%- else -%}
        {{ ansible_architecture }}
      {%- endif -%}

- name: Debug architecture
  ansible.builtin.debug:
    msg: "Using architecture: {{ arch }}"

- name: Set up the repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Restart docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
